[build]
  command = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
